const phrases = [
    "Você é mais forte do que imagina.",
    "Cada passo é uma conquista.",
    "Acredite no seu potencial.",
    "Você é capaz de coisas incríveis.",
    "A jornada é tão importante quanto o destino.",
    "Respire fundo e continue.",
    "Um dia de cada vez.",
    "Você não está sozinho.",
    "Pequenos progressos são grandes vitórias.",
    "Confie em si mesmo.",
    "Seu esforço será recompensado.",
    "Acredite no processo.",
    "Tudo começa com o primeiro passo.",
    "A persistência supera a resistência.",
    "Você é único e especial.",
    "Cada dificuldade é uma oportunidade de crescimento.",
    "O sucesso é a soma de pequenos esforços.",
    "Você tem o poder de mudar sua vida.",
    "Nunca subestime sua capacidade de superar desafios.",
    "Confie no seu caminho.",
    "Você é mais corajoso do que pensa.",
    "Não tenha medo de errar.",
    "Os melhores dias estão por vir.",
    "Você está fazendo um ótimo trabalho.",
    "Aprenda com os desafios.",
    "Você é uma luz no mundo.",
    "Sempre há algo novo para aprender.",
    "Mantenha a fé em si mesmo.",
    "A mudança começa com você.",
    "Você é digno de todas as coisas boas.",
    "Não desista dos seus sonhos.",
    "Você é uma inspiração.",
    "Acredite em dias melhores.",
    "Cada dia é uma nova oportunidade.",
    "Você pode fazer a diferença.",
    "A sua felicidade é importante.",
    "Mantenha a cabeça erguida.",
    "Você tem um propósito.",
    "Vá em frente, você consegue.",
    "Você merece o melhor.",
    "Nunca pare de sonhar.",
    "Sua força está em sua persistência.",
    "Você é mais amado do que imagina.",
    "O impossível é apenas uma opinião.",
    "Você tem o poder de criar seu futuro.",
    "Cada passo em frente é um passo para o sucesso.",
    "Você é uma obra-prima em construção.",
    "Acredite na sua jornada.",
    "Você é uma pessoa incrível.",
    "Não há limites para o que você pode alcançar.",
    "Você está no caminho certo.",
    "Sua determinação é admirável.",
    "Você é mais resiliente do que sabe.",
    "A vida é uma aventura maravilhosa.",
    "Você é uma força da natureza.",
    "Cada dia é uma nova chance para ser feliz.",
    "Você é um vencedor.",
    "Continue brilhando.",
    "Você tem muito a oferecer.",
    "Seu potencial é ilimitado.",
    "Você faz a diferença no mundo.",
    "Nunca subestime o poder do seu sorriso.",
    "Você é capaz de superar qualquer obstáculo.",
    "Seu futuro é brilhante.",
    "Acredite no seu coração.",
    "Você é uma estrela em ascensão.",
    "Cada passo te leva mais perto do seu sonho.",
    "Você é uma fonte de alegria.",
    "Seu esforço vale a pena.",
    "Você tem o poder de transformar.",
    "Confie na magia dos novos começos.",
    "Você é um guerreiro.",
    "Seja gentil consigo mesmo.",
    "Você é uma benção.",
    "A felicidade está ao seu alcance.",
    "Você está crescendo e evoluindo.",
    "Cada desafio é uma nova lição.",
    "Você é uma pessoa maravilhosa.",
    "Tudo é possível para quem acredita.",
    "Você é um exemplo de coragem.",
    "Sua paixão é contagiante.",
    "Você faz a diferença na vida das pessoas.",
    "Acredite na força do amor.",
    "Você é mais do que suficiente.",
    "O sucesso está no seu caminho.",
    "Você é uma inspiração para os outros.",
    "A vida é cheia de possibilidades.",
    "Você tem um coração de ouro.",
    "Nunca perca a esperança.",
    "Você é um raio de luz.",
    "A sua jornada é única.",
    "Você está cercado de amor.",
    "Você é uma fonte de inspiração.",
    "O mundo é um lugar melhor com você.",
    "Você é uma pessoa especial.",
    "Seu potencial é incrível.",
    "Você é uma força positiva.",
    "Você está fazendo a diferença.",
    "O futuro é seu para criar.",
    "Você é uma pessoa de valor.",
    "Acredite na sua intuição.",
    "Você é uma estrela brilhante."
];

let currentIndex = 0;

const supportTextElement = document.getElementById('support-text');

function showNextPhrase() {
    supportTextElement.style.opacity = 0;

    setTimeout(() => {
        supportTextElement.textContent = phrases[currentIndex];
        supportTextElement.style.opacity = 1;
        currentIndex = (currentIndex + 1) % phrases.length;
    }, 2000); 
}

setInterval(showNextPhrase, 30000); 
showNextPhrase();
